### ISSUE TITLE
Error: AttributeError: 'WebClient' object has no attribute 'channel_history'

### ISSUE THREAD

**Issue by avinashsonee** [LouisBrunner/slack-channel-backup#1]
I'm facing this error when executing the following command:

`python slack-backup.py "#xperiences" --where xperiences_bkp`

> Retrieving users...
> Retrieving messages...
> Traceback (most recent call last):
>   File "slack-backup.py", line 199, in <module>
>     main()
>   File "slack-backup.py", line 169, in main
>     messages = read_all_messages(client, 'channel_history', channel, **read_args)
>   File "slack-backup.py", line 16, in read_all_messages
>     func = getattr(client, func_name)
> AttributeError: 'WebClient' object has no attribute 'channel_history'

Environment:
Python **3.7.3**
module version: **slackclient==2.5.0**
OS: Windows 10

**Comment by LouisBrunner** [comment]
Hi @avinashsonee,
Looks like this was a typo, it should be fixed now.
